### ISSUE TITLE
Pi zero w

### ISSUE THREAD

**Issue by cjprecord** [kclyu/rpi-webrtc-streamer-deb#1]
Hello I a very interested in this project. I was testing out the zerow deb package on my pi zero w with v2 camera.

I am able to start the service and connect to it from another computer on lan. When I start a webrtc session I hear the speaker on the pi click but shortly after the CPU seems to get fully saturated and connection drops.

Does this make use of the hw acceleration for h264?

Is there something else I need to configure or setup?

Thanks

**Comment by kclyu** [comment]
The answer is a little late. Normally, deb repo did not come up with an issue and did not watch. I would appreciate it if you upload the issue to rws repo.

RWS uses MMAL hw acceleration for H.264 video encoding.
Please refer to README_audio.md of RWS for audio related setting.

**Comment by cjprecord** [comment]
Hello thanks for the reply will close and repost information to other tracker.
