### ISSUE TITLE
downloaded via curl, dpkg-deb error: 'rws_0.73.2_armhf.db is not a debian format archive! on RPI Stretch Lite

### ISSUE THREAD

**Issue by ezrover** [kclyu/rpi-webrtc-streamer-deb#2]
Step 1: install Stretch Lite on Raspberry pi
Step 2: curl -sLO https://github.com/.........rws_0.73.2_armhf.db
Step3: sudo dpk -i rws_0.73.2_armhf.db

Get error" 'rws_0.73.2_armhf.db' is not a debian format archive

Any thoughts?

**Comment by kclyu** [comment]
Sorry to answer late. 

Generally, if you click the corresponding deb file in github, github provides a download button.
To download it directly,
The URL you are trying to download, such as https://github.com/kclyu/rpi-webrtc-streamer-deb/raw/master/rws_0.73.2_armhf.deb, will have a different URL, such as 'raw / master'.
