### ISSUE TITLE
Custom streaming page

### ISSUE THREAD

**Issue by AlexanderBykin** [kclyu/rpi-webrtc-streamer-deb#5]
Hi
I need custom streaming page:
when the page is opened automatically connect to the camera, there should don't be any controls and the image should be stretched to full screen
how to do that?

**Comment by kclyu** [comment]
all actions on the RWS test page use javascript. Please refer to the np2 or peerconnection under the web-root, and modify it if necessary.

**Comment by AlexanderBykin** [comment]
ok found them at `/opt/rws`
also when i open streaming page from PC and them from Smartphone simultaneously, a can't see any image at Smartphone, is there any connection limits?

**Comment by kclyu** [comment]
Please visit kclyu/rpi-webrtc-streamer#50

For issues other than pkg, please use the kclyu / rpi-webrtc-streamer issue page.

**Comment by AlexanderBykin** [comment]
ok thank you
